### ISSUE TITLE
All models are trained with 50000 episodes

### ISSUE THREAD

**Issue by AmirRezaSobhdel** [khoinguyenucd/LearningToCompare-Tensorflow#1]
you've mentioned that All models are trained with 50000 episodes but in the code, the actual episode count is 500000.
can you please tell me which one is the exact number? 50000 or 500000?

**Comment by khoiucd** [comment]
Thank you for your interest in my work. The config in this code is exactly the same as in the official implementation. It should be 500000. However, the training time is too long and I reduced the number to 50000.

**Comment by AmirRezaSobhdel** [comment]
thank you for the answer
